name: build & push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: timstewartj/personal-site:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.REMOTE_HOST_PROD }}
            username: ${{ secrets.REMOTE_USER_PROD }}
            key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
            port: 22
            script: | 
              cd prog
              ./deploy-personal-site.sh
